import { NextResponse } from "next/server";

export const GET = async () => {
  const menu = [
    {
      name: "Appetizers",
      slug: "appetizers",
      description: "Delicious starters to kick off your meal.",
      image: "https://example.com/appetizer.jpg",
      foodTypes: ["Vegetarian", "Non-Vegetarian"],
      mealType: "Snack",
      allergenInfo: ["Gluten", "Nuts"],
      mealPreferences: ["Vegan", "Low Carb"],
      available: true,
      featured: true,
      priority: 1,
      tags: ["Quick Meals", "Healthy"],
      promotions: [
        {
          promotionTitle: "20% off Appetizers",
          promotionDetails: "Get 20% off on all appetizers.",
          discountPercentage: 20,
          validUntil: "2025-01-31T23:59:59Z",
        },
      ],
      specialOffers: [
        {
          offerTitle: "Buy One Get One Free",
          offerDescription: "Buy one appetizer and get another free.",
          offerValidity: "2025-01-31T23:59:59Z",
        },
      ],
    },
    {
      name: "Desserts",
      slug: "desserts",
      description: "Sweet treats to end your meal.",
      image: "https://example.com/desserts.jpg",
      foodTypes: ["Vegetarian"],
      mealType: "Dessert",
      allergenInfo: ["Dairy"],
      mealPreferences: ["Low Sugar"],
      available: true,
      featured: false,
      priority: 2,
      tags: ["Sweet", "Favorite"],
      promotions: [
        {
          promotionTitle: "10% off Desserts",
          promotionDetails: "Enjoy 10% off on all desserts.",
          discountPercentage: 10,
          validUntil: "2025-02-15T23:59:59Z",
        },
      ],
      specialOffers: [
        {
          offerTitle: "Free Topping",
          offerDescription: "Add a free topping of your choice.",
          offerValidity: "2025-02-15T23:59:59Z",
        },
      ],
    },
    {
      name: "Main Courses",
      slug: "main-courses",
      description: "Satisfying dishes for a hearty meal.",
      image: "https://example.com/main-course.jpg",
      foodTypes: ["Vegetarian", "Non-Vegetarian"],
      mealType: "Dinner",
      allergenInfo: ["Soy"],
      mealPreferences: ["High Protein"],
      available: true,
      featured: true,
      priority: 3,
      tags: ["Filling", "Traditional"],
      promotions: [
        {
          promotionTitle: "Free Side Dish",
          promotionDetails: "Order a main course and get a free side dish.",
          discountPercentage: 0,
          validUntil: "2025-02-28T23:59:59Z",
        },
      ],
      specialOffers: [
        {
          offerTitle: "Loyalty Bonus",
          offerDescription: "Earn double points with every main course.",
          offerValidity: "2025-03-01T23:59:59Z",
        },
      ],
    },
    {
      name: "Breakfast",
      slug: "breakfast",
      description: "Start your day with energy-packed meals.",
      image: "https://example.com/breakfast.jpg",
      foodTypes: ["Vegetarian"],
      mealType: "Breakfast",
      allergenInfo: ["Eggs", "Dairy"],
      mealPreferences: ["Low Fat"],
      available: true,
      featured: false,
      priority: 4,
      tags: ["Morning", "Healthy"],
      promotions: [
        {
          promotionTitle: "Morning Delight",
          promotionDetails: "15% off on all breakfast items.",
          discountPercentage: 15,
          validUntil: "2025-02-10T23:59:59Z",
        },
      ],
      specialOffers: [
        {
          offerTitle: "Free Coffee",
          offerDescription: "Get a free coffee with every breakfast.",
          offerValidity: "2025-02-10T23:59:59Z",
        },
      ],
    },
    {
      name: "Beverages",
      slug: "beverages",
      description: "Quench your thirst with refreshing drinks.",
      image: "https://example.com/beverages.jpg",
      foodTypes: ["Vegetarian"],
      mealType: "Drink",
      allergenInfo: [],
      mealPreferences: ["Sugar-Free", "Caffeine-Free"],
      available: true,
      featured: true,
      priority: 5,
      tags: ["Refreshing", "Cool"],
      promotions: [
        {
          promotionTitle: "2-for-1 Drinks",
          promotionDetails: "Buy one drink and get another free.",
          discountPercentage: 50,
          validUntil: "2025-02-20T23:59:59Z",
        },
      ],
      specialOffers: [
        {
          offerTitle: "Happy Hour",
          offerDescription: "Drinks at half price between 4-6 PM.",
          offerValidity: "2025-03-01T23:59:59Z",
        },
      ],
    },
    {
      name: "Salads",
      slug: "salads",
      description: "Fresh and healthy salads for a balanced diet.",
      image: "https://example.com/salads.jpg",
      foodTypes: ["Vegetarian", "Vegan"],
      mealType: "Side",
      allergenInfo: ["Nuts", "Seeds"],
      mealPreferences: ["Low Calorie"],
      available: true,
      featured: false,
      priority: 6,
      tags: ["Healthy", "Fresh"],
      promotions: [
        {
          promotionTitle: "25% off Salads",
          promotionDetails: "Get 25% off on fresh salads.",
          discountPercentage: 25,
          validUntil: "2025-02-28T23:59:59Z",
        },
      ],
      specialOffers: [
        {
          offerTitle: "Combo Deal",
          offerDescription: "Pair a salad with any meal and save 10%.",
          offerValidity: "2025-03-15T23:59:59Z",
        },
      ],
    },
    {
      name: "Pizzas",
      slug: "pizzas",
      description: "Hot, cheesy pizzas with a variety of toppings.",
      image: "https://example.com/pizzas.jpg",
      foodTypes: ["Vegetarian", "Non-Vegetarian"],
      mealType: "Dinner",
      allergenInfo: ["Gluten", "Dairy"],
      mealPreferences: ["Cheese-Lovers", "Low Carb"],
      available: true,
      featured: true,
      priority: 7,
      tags: ["Cheesy", "Family Meals"],
      promotions: [
        {
          promotionTitle: "Pizza Night Deal",
          promotionDetails: "Buy two pizzas and get one free.",
          discountPercentage: 33,
          validUntil: "2025-02-28T23:59:59Z",
        },
      ],
      specialOffers: [
        {
          offerTitle: "Extra Topping Free",
          offerDescription: "Get a free topping of your choice.",
          offerValidity: "2025-03-10T23:59:59Z",
        },
      ],
    },
    {
      name: "Soups",
      slug: "soups",
      description: "Warm and comforting bowls of soup.",
      image: "https://example.com/soups.jpg",
      foodTypes: ["Vegetarian", "Non-Vegetarian"],
      mealType: "Starter",
      allergenInfo: ["Dairy", "Soy"],
      mealPreferences: ["Low Sodium"],
      available: true,
      featured: false,
      priority: 8,
      tags: ["Comfort Food", "Healthy"],
      promotions: [
        {
          promotionTitle: "Soup Combo Offer",
          promotionDetails: "Add soup to any meal for just $2.",
          discountPercentage: 50,
          validUntil: "2025-03-15T23:59:59Z",
        },
      ],
      specialOffers: [
        {
          offerTitle: "Unlimited Soup",
          offerDescription: "Enjoy unlimited refills for one price.",
          offerValidity: "2025-03-20T23:59:59Z",
        },
      ],
    },
    {
      name: "Burgers",
      slug: "burgers",
      description: "Juicy burgers with fresh ingredients.",
      image: "https://example.com/burgers.jpg",
      foodTypes: ["Vegetarian", "Non-Vegetarian"],
      mealType: "Snack",
      allergenInfo: ["Gluten", "Dairy"],
      mealPreferences: ["High Protein"],
      available: true,
      featured: true,
      priority: 9,
      tags: ["Comfort Food", "Quick Bite"],
      promotions: [
        {
          promotionTitle: "Burger Bundle",
          promotionDetails: "Buy two burgers and get fries free.",
          discountPercentage: 20,
          validUntil: "2025-03-31T23:59:59Z",
        },
      ],
      specialOffers: [
        {
          offerTitle: "Special Patty Upgrade",
          offerDescription: "Upgrade to a double patty for free.",
          offerValidity: "2025-03-10T23:59:59Z",
        },
      ],
    },
    {
      name: "Wraps",
      slug: "wraps",
      description: "Light and flavorful wraps, perfect on-the-go.",
      image: "https://example.com/wraps.jpg",
      foodTypes: ["Vegetarian", "Non-Vegetarian"],
      mealType: "Snack",
      allergenInfo: ["Gluten"],
      mealPreferences: ["Low Calorie"],
      available: true,
      featured: false,
      priority: 10,
      tags: ["Healthy", "Quick Bite"],
      promotions: [
        {
          promotionTitle: "Wrap Wednesday",
          promotionDetails: "All wraps at 25% off every Wednesday.",
          discountPercentage: 25,
          validUntil: "2025-03-31T23:59:59Z",
        },
      ],
      specialOffers: [
        {
          offerTitle: "Free Drink with Wrap",
          offerDescription: "Get a free drink with every wrap.",
          offerValidity: "2025-04-01T23:59:59Z",
        },
      ],
    },
    {
      name: "Ice Creams",
      slug: "ice-creams",
      description: "Cold, creamy delights in various flavors.",
      image: "https://example.com/ice-creams.jpg",
      foodTypes: ["Vegetarian"],
      mealType: "Dessert",
      allergenInfo: ["Dairy"],
      mealPreferences: ["Low Sugar"],
      available: true,
      featured: true,
      priority: 11,
      tags: ["Sweet", "Refreshing"],
      promotions: [
        {
          promotionTitle: "Sundae Special",
          promotionDetails: "Buy one sundae, get another half price.",
          discountPercentage: 50,
          validUntil: "2025-02-28T23:59:59Z",
        },
      ],
      specialOffers: [
        {
          offerTitle: "Free Cone Upgrade",
          offerDescription: "Upgrade your scoop to a cone for free.",
          offerValidity: "2025-03-05T23:59:59Z",
        },
      ],
    },
    {
      name: "Sandwiches",
      slug: "sandwiches",
      description: "Freshly made sandwiches for any time of the day.",
      image: "https://example.com/sandwiches.jpg",
      foodTypes: ["Vegetarian", "Non-Vegetarian"],
      mealType: "Snack",
      allergenInfo: ["Gluten"],
      mealPreferences: ["Low Carb"],
      available: true,
      featured: false,
      priority: 12,
      tags: ["Quick Bite", "Healthy"],
      promotions: [
        {
          promotionTitle: "Lunch Combo",
          promotionDetails: "Sandwich with chips and a drink for $10.",
          discountPercentage: 15,
          validUntil: "2025-03-15T23:59:59Z",
        },
      ],
      specialOffers: [
        {
          offerTitle: "Extra Cheese Free",
          offerDescription: "Add extra cheese to any sandwich at no cost.",
          offerValidity: "2025-03-20T23:59:59Z",
        },
      ],
    },
    {
      name: "Pasta",
      slug: "pasta",
      description: "Rich and savory pasta dishes for every palate.",
      image: "https://example.com/pasta.jpg",
      foodTypes: ["Vegetarian", "Non-Vegetarian"],
      mealType: "Dinner",
      allergenInfo: ["Gluten", "Dairy"],
      mealPreferences: ["Low Fat"],
      available: true,
      featured: true,
      priority: 13,
      tags: ["Comfort Food", "Traditional"],
      promotions: [
        {
          promotionTitle: "Pasta Feast",
          promotionDetails: "20% off on family-sized pasta orders.",
          discountPercentage: 20,
          validUntil: "2025-04-01T23:59:59Z",
        },
      ],
      specialOffers: [
        {
          offerTitle: "Extra Garlic Bread",
          offerDescription: "Free garlic bread with every pasta order.",
          offerValidity: "2025-04-05T23:59:59Z",
        },
      ],
    },
    {
      name: "Fries",
      slug: "fries",
      description: "Crispy golden fries to complement any meal.",
      image: "https://example.com/fries.jpg",
      foodTypes: ["Vegetarian"],
      mealType: "Side",
      allergenInfo: [],
      mealPreferences: ["Low Salt"],
      available: true,
      featured: true,
      priority: 14,
      tags: ["Snack", "Crispy"],
      promotions: [
        {
          promotionTitle: "Fries Frenzy",
          promotionDetails: "Buy one large fries and get one free.",
          discountPercentage: 50,
          validUntil: "2025-03-10T23:59:59Z",
        },
      ],
      specialOffers: [
        {
          offerTitle: "Spicy Upgrade",
          offerDescription: "Add a spicy seasoning for free.",
          offerValidity: "2025-03-20T23:59:59Z",
        },
      ],
    },
    {
      name: "Main Course",
      slug: "main-course",
      description: "Hearty and fulfilling dishes to satisfy your hunger.",
      image: "https://example.com/main-course.jpg",
      foodTypes: ["Vegetarian", "Non-Vegetarian"],
      mealType: "Lunch/Dinner",
      allergenInfo: ["Dairy", "Soy"],
      mealPreferences: ["High Protein", "Low Fat"],
      available: true,
      featured: true,
      priority: 2,
      tags: ["Comfort Food", "Family Meals"],
      promotions: [
        {
          promotionTitle: "15% off Mains",
          promotionDetails: "Enjoy a 15% discount on all main courses.",
          discountPercentage: 15,
          validUntil: "2025-02-15T23:59:59Z",
        },
      ],
      specialOffers: [
        {
          offerTitle: "Free Dessert",
          offerDescription: "Get a free dessert with every main course.",
          offerValidity: "2025-02-15T23:59:59Z",
        },
      ],
    },
    {
      name: "Desserts",
      slug: "desserts",
      description: "Sweet treats to end your meal on a high note.",
      image: "https://example.com/desserts.jpg",
      foodTypes: ["Vegetarian"],
      mealType: "Dessert",
      allergenInfo: ["Gluten", "Dairy"],
      mealPreferences: ["Sugar-Free", "Low Carb"],
      available: true,
      featured: true,
      priority: 3,
      tags: ["Sweet Delights", "Indulgent"],
      promotions: [
        {
          promotionTitle: "10% off Desserts",
          promotionDetails: "Relish a 10% discount on all desserts.",
          discountPercentage: 10,
          validUntil: "2025-03-01T23:59:59Z",
        },
      ],
      specialOffers: [
        {
          offerTitle: "Combo Offer",
          offerDescription: "Add a dessert to your main course at 50% off.",
          offerValidity: "2025-03-01T23:59:59Z",
        },
      ],
    },
    {
      name: "Beverages",
      slug: "beverages",
      description: "Refreshing drinks to complement your meal.",
      image: "https://example.com/beverages.jpg",
      foodTypes: ["Vegan", "Vegetarian"],
      mealType: "Drink",
      allergenInfo: ["None"],
      mealPreferences: ["Low Sugar", "Gluten-Free"],
      available: true,
      featured: false,
      priority: 4,
      tags: ["Cold Drinks", "Hot Beverages"],
      promotions: [
        {
          promotionTitle: "Free Beverage",
          promotionDetails: "Get a free beverage with orders above $50.",
          discountPercentage: 100,
          validUntil: "2025-01-25T23:59:59Z",
        },
      ],
      specialOffers: [
        {
          offerTitle: "Drink of the Day",
          offerDescription: "Get 20% off the drink of the day.",
          offerValidity: "2025-01-25T23:59:59Z",
        },
      ],
    },
    {
      name: "Salads",
      slug: "salads",
      description: "Fresh and healthy salads made with seasonal ingredients.",
      image: "https://example.com/salads.jpg",
      foodTypes: ["Vegetarian", "Vegan"],
      mealType: "Snack/Side Dish",
      allergenInfo: ["Nuts", "Soy"],
      mealPreferences: ["Gluten-Free", "Low Calorie"],
      available: true,
      featured: true,
      priority: 5,
      tags: ["Healthy Options", "Quick Bites"],
      promotions: [
        {
          promotionTitle: "Salad Special",
          promotionDetails: "Save 25% on all salads this week.",
          discountPercentage: 25,
          validUntil: "2025-01-28T23:59:59Z",
        },
      ],
      specialOffers: [
        {
          offerTitle: "Lunch Combo",
          offerDescription:
            "Add a salad to your main course at a special price.",
          offerValidity: "2025-01-28T23:59:59Z",
        },
      ],
    },
    {
      name: "Soups",
      slug: "soups",
      description: "Warm and comforting soups for any occasion.",
      image: "https://example.com/soups.jpg",
      foodTypes: ["Vegetarian", "Non-Vegetarian"],
      mealType: "Starter",
      allergenInfo: ["Dairy", "Gluten"],
      mealPreferences: ["Low Fat", "High Protein"],
      available: true,
      featured: false,
      priority: 6,
      tags: ["Comfort Food", "Healthy"],
      promotions: [
        {
          promotionTitle: "Soup of the Day",
          promotionDetails: "Try the soup of the day at 30% off.",
          discountPercentage: 30,
          validUntil: "2025-02-01T23:59:59Z",
        },
      ],
      specialOffers: [
        {
          offerTitle: "Free Breadsticks",
          offerDescription: "Enjoy free breadsticks with every soup.",
          offerValidity: "2025-02-01T23:59:59Z",
        },
      ],
    },
    {
      name: "Breakfast",
      slug: "breakfast",
      description: "Start your day with our wholesome breakfast options.",
      image: "https://example.com/breakfast.jpg",
      foodTypes: ["Vegetarian", "Non-Vegetarian"],
      mealType: "Breakfast",
      allergenInfo: ["Eggs", "Gluten"],
      mealPreferences: ["Low Sugar", "High Protein"],
      available: true,
      featured: true,
      priority: 7,
      tags: ["Morning Meals", "Healthy Start"],
      promotions: [
        {
          promotionTitle: "Breakfast Deal",
          promotionDetails: "Flat 20% off on all breakfast items.",
          discountPercentage: 20,
          validUntil: "2025-02-10T23:59:59Z",
        },
      ],
      specialOffers: [
        {
          offerTitle: "Family Breakfast Offer",
          offerDescription: "Buy breakfast for 4 and pay for 3.",
          offerValidity: "2025-02-10T23:59:59Z",
        },
      ],
    },
  ];

  return NextResponse.json(menu);
};